### ISSUE TITLE
extract_random_effect did not yield confidence intervals for nlme object 

### ISSUE THREAD

**Issue by tapirus07** [m-clark/mixedup#9]
mixedup::extract_random_efects does not report condfidence intervals for nlme object. It is not working for nonlinear models even though the documentation inform that fucntion can handle with this objects.

mod=nlme(y~Asym/exp((xmid-x)/scal), 
data=data, 
fixed = Asym+xmid+scal ~ 1,
random = Asym+xmid+scal~1|country,
)

extract_random_effect(mod)
   group_var effect group         value
   <chr>     <chr>  <chr>         <dbl>
 1 country   Asym   Afghanistan -13353.
 2 country   Asym   Algeria     -11859.
 3 country   Asym   Andorra      -5100.
 4 country   Asym   Argentina      337.
 5 country   Asym   Armenia      -4778.
 6 country   Asym   Australia    -7036.
 7 country   Asym   Austria       1543.
 8 country   Asym   Azerbaijan  -11756.
 9 country   Asym   Bahrain     -13132.
10 country   Asym   Belarus     -12661.
# ... with 275 more rows

Any alternative or solution?

**Comment by m-clark** [comment]
There are no random effects for nlme, because it doesn't provide even a standard error.  In the helpfile it states "The nlme package only provides the estimated random effect parameters, not their uncertainty, so it isn't provided."

The brms package may be able to do this model for you, at which point you should be able to get the interval estimate.

**Comment by m-clark** [comment]
Going ahead and closing as the function is working as documented, but feel free to post if something else is amiss.
